# 1.What is pytorch?
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
## Tensors

In [1]:
import torch

In [2]:
#if uninitialized, this have some value.
x=torch.empty(5,3)
print(x)

tensor([[7.1441e+31, 6.9987e+22, 7.8675e+34],
        [4.7418e+30, 5.9663e-02, 7.0374e+22],
        [0.0000e+00, 0.0000e+00, 2.5113e-22],
        [1.5573e-41, 3.1529e-43, 0.0000e+00],
        [2.5113e-22, 1.5573e-41, 2.5113e-22]])


In [3]:
#randomly initialized
x=torch.rand(5,3)
print(x)

tensor([[0.7760, 0.8155, 0.0198],
        [0.6607, 0.6425, 0.1983],
        [0.8132, 0.2384, 0.9661],
        [0.3181, 0.7546, 0.6642],
        [0.5317, 0.7438, 0.1732]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float) #override dtyep
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0417e+00, -4.2395e-01, -4.6977e-01],
        [-8.5206e-01,  1.8481e+00, -1.1598e+00],
        [-9.3262e-01, -1.0041e-01,  1.8088e-03],
        [ 1.6995e+00, -2.8601e-01,  6.2079e-02],
        [ 6.2480e-01, -1.7864e+00,  5.2032e-01]])


In [7]:
print(x.size())

torch.Size([5, 3])


## Operations
Except below, 100+ Tensor operations exist

In [8]:
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)
print(torch.add(x,y))

tensor([[-1.0417e+00, -4.2395e-01, -4.6977e-01],
        [-8.5206e-01,  1.8481e+00, -1.1598e+00],
        [-9.3262e-01, -1.0041e-01,  1.8088e-03],
        [ 1.6995e+00, -2.8601e-01,  6.2079e-02],
        [ 6.2480e-01, -1.7864e+00,  5.2032e-01]])
tensor([[0.7918, 0.4479, 0.6581],
        [0.4492, 0.9862, 0.9119],
        [0.3979, 0.7009, 0.7832],
        [0.7911, 0.8850, 0.3726],
        [0.7424, 0.6423, 0.3573]])
tensor([[-0.2499,  0.0239,  0.1883],
        [-0.4029,  2.8343, -0.2479],
        [-0.5348,  0.6005,  0.7851],
        [ 2.4906,  0.5990,  0.4347],
        [ 1.3672, -1.1441,  0.8776]])
tensor([[-0.2499,  0.0239,  0.1883],
        [-0.4029,  2.8343, -0.2479],
        [-0.5348,  0.6005,  0.7851],
        [ 2.4906,  0.5990,  0.4347],
        [ 1.3672, -1.1441,  0.8776]])


In [9]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.2499,  0.0239,  0.1883],
        [-0.4029,  2.8343, -0.2479],
        [-0.5348,  0.6005,  0.7851],
        [ 2.4906,  0.5990,  0.4347],
        [ 1.3672, -1.1441,  0.8776]])


In [10]:
print(x[:,1])

tensor([-0.4240,  1.8481, -0.1004, -0.2860, -1.7864])


In [11]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) #the size -1 is inferred from other dimensions
z_ = x.view(8, -1)
print(x.size(), y.size(), z.size(), z_.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([8, 2])


In [12]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7899])
-0.7898663282394409


## NumPy Bridge
### Converting Torch Tensor to a NumPy Array

In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b=a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


### Converting NumPy Array to Torch Tensor

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [16]:
#let us run this cell only if CUDA is available
#We will use ''torch.device'' objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) #directly create a tensor on GPU
    x = x.to(device) #or just use strings ''.to("cuda")''
    z = x+y
    print(z)
    print(z.to("cpu", torch.double)) #''.to'' can also change dtype together!

tensor([0.2101], device='cuda:0')
tensor([0.2101], dtype=torch.float64)


# 2.Autograd: Automatic differentiation
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py
## Tensor

In [17]:
import torch

In [18]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [20]:
print(y.grad_fn)

In [21]:
z = y* y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [22]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## Gradients

In [23]:
out.backward() #back-prop
print(x.grad) #∂out/∂x_i (x_i=1)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [24]:
x = torch.randn(3, requires_grad=True)

y=x*2
while y.data.norm()<1000: #cal L2norm
    y = y*2
    
print(y)

tensor([1396.6777,  826.9160,  210.4431], grad_fn=<MulBackward0>)


In [25]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [26]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [27]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


## autograd.Functions
https://pytorch.org/docs/stable/autograd.html#function