# 1.What is pytorch?
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
## Tensors

In [1]:
import torch

In [5]:
#if uninitialized, this have some value.
x=torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 7.2646e+22],
        [7.2250e+28, 2.5226e-18, 2.4283e-18],
        [2.6302e+20, 6.1949e-04, 1.0256e-08],
        [1.6408e-07, 3.0613e+12, 6.7738e-10],
        [1.0802e-05, 2.6659e-09, 1.2962e+16]])


In [2]:
#randomly initialized
x=torch.rand(5,3)
print(x)

tensor([[0.3907, 0.3430, 0.4469],
        [0.7971, 0.5439, 0.4511],
        [0.6859, 0.5481, 0.6183],
        [0.8793, 0.4338, 0.2857],
        [0.5927, 0.4282, 0.3813]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float) #override dtyep
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5515, -0.0436, -0.2227],
        [ 0.4507, -0.8139,  0.9860],
        [-0.2310,  1.0108,  0.3963],
        [ 0.7350, -0.9518,  0.1248],
        [-0.4270,  0.7035,  0.5806]])


In [12]:
print(x.size())

torch.Size([5, 3])


## Operations
Except below, 100+ Tensor operations exist

In [21]:
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)
print(torch.add(x,y))

tensor([[0.6949, 0.1252, 0.9872],
        [0.7668, 0.8440, 0.7044],
        [0.9847, 0.4382, 0.4754],
        [0.2306, 0.0561, 0.8694],
        [0.2125, 0.5910, 0.1344]])
tensor([[0.2503, 0.7707, 0.7599],
        [0.3757, 0.8038, 0.6250],
        [0.4841, 0.8559, 0.1912],
        [0.4563, 0.5855, 0.7725],
        [0.6335, 0.4826, 0.5339]])
tensor([[0.9452, 0.8959, 1.7471],
        [1.1425, 1.6479, 1.3295],
        [1.4688, 1.2941, 0.6666],
        [0.6869, 0.6415, 1.6419],
        [0.8459, 1.0736, 0.6683]])
tensor([[0.9452, 0.8959, 1.7471],
        [1.1425, 1.6479, 1.3295],
        [1.4688, 1.2941, 0.6666],
        [0.6869, 0.6415, 1.6419],
        [0.8459, 1.0736, 0.6683]])


In [22]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.9452, 0.8959, 1.7471],
        [1.1425, 1.6479, 1.3295],
        [1.4688, 1.2941, 0.6666],
        [0.6869, 0.6415, 1.6419],
        [0.8459, 1.0736, 0.6683]])


In [23]:
print(x[:,1])

tensor([0.1252, 0.8440, 0.4382, 0.0561, 0.5910])


In [28]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) #the size -1 is inferred from other dimensions
z_ = x.view(8, -1)
print(x.size(), y.size(), z.size(), z_.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([8, 2])


In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3759])
1.3758717775344849


## NumPy Bridge
### Converting Torch Tensor to a NumPy Array

In [30]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b=a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


### Converting NumPy Array to Torch Tensor

In [32]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [33]:
#let us run this cell only if CUDA is available
#We will use ''torch.device'' objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) #directly create a tensor on GPU
    x = x.to(device) #or just use strings ''.to("cuda")''
    z = x+y
    print(z)
    print(z.to("cpu", torch.double)) #''.to'' can also change dtype together!

# 2.Autograd: Automatic differentiation
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py
## Tensor

In [67]:
import torch

In [68]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [69]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [70]:
print(y.grad_fn)

In [71]:
z = y* y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [72]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## Gradients

In [73]:
out.backward() #back-prop
print(x.grad) #∂out/∂x_i (x_i=1)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [74]:
x = torch.randn(3, requires_grad=True)

y=x*2
while y.data.norm()<1000: #cal L2norm
    y = y*2
    
print(y)

tensor([-1048.4713,  -930.2204,  -248.9130], grad_fn=<MulBackward0>)


In [76]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [65]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [77]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


## autograd.Functions
https://pytorch.org/docs/stable/autograd.html#function